project:
  type: website

website:
  title: "REL-Physique"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd
      - minkowski.qmd
      - michelsonmorley.qmd
      - projectile.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    highlight-style: github



