project:
  type: website

website:
  title: "REL-Physique"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - minkowski.qmd
      - michelsonmorley.qmd
      - projectile.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



